name: JFrog CLI Core Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
      GOPROXY: direct
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: pip3 install pipenv
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: Lint
        run: go vet ./...
      - name: Tests
        run: go test -v github.com/jfrog/jfrog-cli-core/v2/tests -timeout 0
